### ISSUE TITLE
Customize documentation generation

### ISSUE THREAD

**Issue by aruZeta** [aruZeta/QRgen#3]
- [x] Cmd:
  - [x] Create a nimble task with the command
  - [x] Discern between docs pointing to main and develop
- [ ] Config:
  - [ ] Custom html
  - [ ] Custom css
- [x] Actions:
  - [x] Add an overlay to the nim pkg in `shell.nix` to add the `tools/` directory and compile dochack.
  - [x] Create a GitHub action to build the documentation
    There should be a distinction between docs of main/stable and develop/unstable.
    - [x] Main docs
    - [x] Develop docs
    - [x] Create a main page or some way to select which branch to read the docs from

**Comment by aruZeta** [comment]
My bad, last 2 commits referenced the wrong issue, rebased those commits but doesn't seem to disappear from here.

**Comment by aruZeta** [comment]
Actually I'm moving the nix flake task to it's own issue, #7

**Comment by aruZeta** [comment]
About customizing the html and css generation, that can be done later since it's not that important, closing the issue for now.
