### ISSUE TITLE
Use a nix flake instead of shell.nix

### ISSUE THREAD

**Issue by aruZeta** [aruZeta/QRgen#7]
- [x] Make the actual shell.nix into a flake
- [ ] Create a derivation to generate develop branch documentation
- [ ] Create a derivation to generate develop main documentation
- [ ] Create a derivation to run tests
- [ ] Create a derivation to run benchmarks

**Comment by aruZeta** [comment]
So after a bit of research and finishing the flake with nim 1.6.6 and fixed nim-unwrapped build, I think that creating derivations for running tests, benchmarks or doc generation is not the best approach, and doing `nix shell -c nim/nimble command` would be best to use in GitHub actions, while for local development you could use `nix develop`.

I also have not been able to achieve creating those derivations, which is also why I'm changing the approach, if I'm able to do it I will reconsider doing it that way or not.
