### ISSUE TITLE
Add GitHub action to check if tests pass

### ISSUE THREAD

**Issue by aruZeta** [aruZeta/QRgen#9]
- [x] Create a nimble task for running tests (don't like the default one)
- [x] Create the action
- [x] Doc generation workflow runs only when the tests have passed or when there was a push to main

**Comment by aruZeta** [comment]
Also would be nice to make the doc generation workflow run only when the tests have passed or when there was a push to main.

**Comment by aruZeta** [comment]
Seems like it works, but it's not actually listed in the commit's run workflows:
![Image](https://user-images.githubusercontent.com/68018085/187788103-d5f820bb-e2a2-4f1b-9aa9-79cf4410519d.png)

**Comment by aruZeta** [comment]
Also I actually only pushed the inputs of the flake to my cachix cache, so nim had to be built all over again and the action took around 8-10 minutes.

I have already pushed the actual outputs and now the actions seem to take around 2 mins!

So, since all the tasks have been completing, I'm closing this issue.
